apiVersion: v1
kind: Secret
metadata:
  name: github-runner-token
  namespace: github-runners
type: Opaque
data:
  token: QUUySVdOQTQ2TzY0NjRaRlZKV0pCQTNIWkpJVk0= # base64 encoded token AE2IWNA46O6464ZFVJWJBA3HZJIVM